# Generated by Django 5.0.3 on 2024-03-09 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_block', models.TextField(verbose_name='Инфоблок о компании')),
            ],
            options={
                'verbose_name': 'Инфоблок о компании',
                'verbose_name_plural': 'Инфоблок о компании',
            },
        ),
        migrations.CreateModel(
            name='CompanyAdvantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advantage', models.TextField(verbose_name='Преимущество')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
            },
        ),
        migrations.CreateModel(
            name='CompanyDecisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(max_length=255, verbose_name='Предлагаемые нами решения')),
            ],
            options={
                'verbose_name': 'Наше решение',
                'verbose_name_plural': 'Наши решения',
            },
        ),
        migrations.CreateModel(
            name='CompanyExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stack', models.CharField(max_length=255, verbose_name='Стек технологий')),
                ('description', models.TextField(verbose_name='Описание стека')),
            ],
            options={
                'verbose_name': 'Стек технологий',
                'verbose_name_plural': 'Стек технологий',
            },
        ),
        migrations.CreateModel(
            name='CompanyInfoAndContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('slogan', models.TextField(verbose_name='Девиз компании')),
                ('opening_hours', models.CharField(max_length=50, verbose_name='Время работы')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone_number', models.CharField(max_length=25, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Компания и контакты',
                'verbose_name_plural': 'Компания и контакты',
            },
        ),
        migrations.CreateModel(
            name='CompanyProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('image', models.ImageField(upload_to='./project_img', verbose_name='Обложка проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='ProjectResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=255, verbose_name='Результат по проекту')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.companyprojects', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Результаты по проекту',
                'verbose_name_plural': 'Результаты по проекту',
            },
        ),
    ]
