# Generated by Django 5.0.3 on 2024-03-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprojects',
            name='link',
            field=models.CharField(default='#', max_length=255, verbose_name='Ссылка на сайт'),
        ),
    ]
