# Generated by Django 5.0.3 on 2024-03-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_companyprojects_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyadvantages',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='companyadvantages',
            name='advantage',
            field=models.CharField(max_length=255, verbose_name='Преимущество'),
        ),
    ]
