# Generated by Django 5.0 on 2024-04-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_companyadvantages_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='./employees_img', verbose_name='Фото сотрудника')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО сотрудника')),
                ('job_title', models.CharField(max_length=255, verbose_name='Должность сотрудника')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
